### ISSUE TITLE
No autocomplete for the 2nd hard of subquery time selector

### ISSUE THREAD

**Issue by roidelapluie** [prometheus-community/codemirror-promql#113]
We have auto complete on [**5m**:5m] but not on [5m:**5m**]

autocomplete:
![auto1](https://user-images.githubusercontent.com/291750/112212297-16d61080-8c1d-11eb-8e9c-e660ba6655df.png)

no autocomplete:
![auto2](https://user-images.githubusercontent.com/291750/112212301-176ea700-8c1d-11eb-8489-e3c535688f34.png)

**Comment by Nexucis** [comment]
oh my :o you already find an issue in this lib.

So fast. Thanks for it :), this is definitely something missed indeed.
