### ISSUE TITLE
Add the parameters of the function indescription

### ISSUE THREAD

**Issue by roidelapluie** [prometheus-community/codemirror-promql#118]
When using `topk` or `bottomk`, there is no snippet. The help text does not show the order of those arguments.

We could either add the parameters in the tooltip or have more snippets.

**Comment by juliusv** [comment]
@roidelapluie I'm all for more snippets, feel free to add more at https://github.com/prometheus-community/codemirror-promql/blob/b238d38fe2442757d1baa9859f1cb3989bea9344/src/lang-promql/complete/promql.terms.ts#L448-L470

But showing more info in the help text is also a good idea. For functions (which `topk` is not), we even have a list already of all their signatures, which we could use to generate the help text automatically: https://github.com/prometheus-community/codemirror-promql/blob/master/src/lang-promql/types/function.ts

In PromLens I also have a separate list of function argument names (so far only used in the tree view).

**Comment by Nexucis** [comment]
I'm wondering if we should provide a way to add custom snippets instead.

Like that you won't have to modify the lib to provide your snippets. It's
good to have a longer default list of snippets, but maybe even on
Prometheus' side, you would prefer to provide your own custom list.

And of course we can do both (i.e. modify the default list + provide a way
to inject more)

Le jeu. 25 mars 2021 à 11:35, Julius Volz ***@***.***> a
écrit :
