### ISSUE TITLE
Support autocompleting NaN and Inf

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/codemirror-promql#136]
Currently when I start typing `NaN` or `Inf` in positions where they are allowed (anywhere where scalar values are allowed, which could be positions where vectors are also allowed), I only get metric names as autocompletion results. It would be great if we could autocomplete `NaN` and `Inf` as well (capitalized or not).

**Comment by Nexucis** [comment]
I think it will require to determinate when to autocomplete a scalar. Which isn't the case today but feasible :)
