### ISSUE TITLE
Support variable format 

### ISSUE THREAD

**Issue by Nexucis** [prometheus-community/codemirror-promql#138]
It would be cool if this plugin can support a variable format. Like `$MyVariable`.

Like that it would be possible to use it in a software like Grafana where you can have variables.
Autocompletion should be able to autocomplete the variable and linter should not raise an error in case a variable is used.

I believe lezer-promql need to be updated as well even if I have no idea how it can support such kind of things. Maybe like an extension that you can activate or not ?

**Comment by juliusv** [comment]
Note that it's always possible that `$` could get a meaning in a future version of PromQL. But still, as an option, it could make sense here.

In lezer, maybe the dialects feature can help, but I haven't looked into this deeply yet: https://lezer.codemirror.net/docs/guide/#dialects

**Comment by Nexucis** [comment]
well I was proposing to prefix a variable by `$`  but if one day it's used in PromQL, it can be changed with other things like `{{ }}` like in the Golang template

**Comment by Nexucis** [comment]
but definitely `$` is  the simpler I think

**Comment by Nexucis** [comment]
I don't think it's feasible at this level unfortunately. I'm not even sure if it's actually feasible if you are using a grammar even after pre-processing all variable.

closing this issue as it's unlikely produce something interesting
