### ISSUE TITLE
Cannot parse metrics beginning with `inf`

### ISSUE THREAD

**Issue by faceair** [prometheus-community/codemirror-promql#140]
![image](https://user-images.githubusercontent.com/3659110/116002584-060a2780-a62d-11eb-96fa-295a3c413a80.png)
It looks like the syntax parsing for metric names starting with `inf` will determine that it is the `Inf` in mathematics.

**Comment by juliusv** [comment]
Thanks, taking a look at it in https://github.com/promlabs/lezer-promql, which is where the issue is.

**Comment by faceair** [comment]
Okay, I created issue under the lezer-promql repository. https://github.com/promlabs/lezer-promql/issues/33
