### ISSUE TITLE
How to make the editor read only?

### ISSUE THREAD

**Issue by puneeth8994** [prometheus-community/codemirror-promql#145]
Is there a way to make the editor read only?

I can see the readOnly option in code mirror but not sure about how to use it using this library.

**Comment by juliusv** [comment]
Yeah, just include this in your CodeMirror extensions, alongside the PromQL extension:

```typescript
EditorView.editable.of(false)
```

**Comment by juliusv** [comment]
Closing the issue here since it's not related to the extension directly, but hoping it solves your question!
