### ISSUE TITLE
Version 17 The api that a package depends on does not exist

### ISSUE THREAD

**Issue by Szq20** [prometheus-community/codemirror-promql#149]
<img width="500" alt="WeChat215d9028cca6c40826751e94e6e61c6c" src="https://user-images.githubusercontent.com/62061488/133399232-2edcb8df-789f-42d7-8a7e-9fa5c8605bc3.png">
<img width="500" alt="WeChatbd23db665ff1a29690ea86c34b081faa" src="https://user-images.githubusercontent.com/62061488/133399455-ae0eaae4-1bac-4890-b371-cf12d1089237.png">

’src/Packages/Demo/node_modules/codemirror-promql/esm/promql.js‘  depends on LezerLanguage but @codemirror/language does not exist

**Comment by Nexucis** [comment]
yup that's because you are using codemirror v0.19. `codemirror-promql` depends on v0.18.

**Comment by Nexucis** [comment]
At some point we will upgrade the codemirror dependencies to the last one, so you can use it as well. But for the moment you will have to use the previous version.

Which isn't so bad. The big changes between v0.18 and v0.19 is the renaming of the `lezer` dependency. (which is a breaking change, that explain why you can't use the last version of codemirror with `codemirror-promql`)

**Comment by guguji5** [comment]
I try to install the peer dependency following the [readme](https://www.npmjs.com/package/codemirror-promql) with below cmd.

`npm install --save @codemirror/autocomplete @codemirror/highlight @codemirror/language @codemirror/lint @codemirror/state @codemirror/view`

Some error happened.  After several hours struggling.

"codemirror-promql": "^0.17.0"` can work with below version of  peer dependency 

```
"@codemirror/basic-setup": "^0.18.0",
  "@codemirror/autocomplete": "^0.18.3",
  "@codemirror/highlight": "^0.18.3",
  "@codemirror/language": "^0.18.0",
  "@codemirror/lint": "^0.18.1",
  "@codemirror/state": "^0.18.2",
  "@codemirror/view": "^0.18.1",
```

**Comment by Nexucis** [comment]
yeah for the moment the situation is not well confortable. But hopefully we will upgrade the dependencies to the last version, and it will be back to an "ok" situation
