### ISSUE TITLE
Update codemirror dependencies to v0.19

### ISSUE THREAD

**Issue by dsmith3197** [prometheus-community/codemirror-promql#150]
Can we update the codemirror dependencies to v0.19? It looks like v0.19 fixes a bug that can put the editor into a corrupted state.

In particular, with v0.18, I'm experiencing a bug that makes the editor completely unusable.  It occurs when both linting and syntax highlighting are enabled. 

See changelog for the bug fix.
```
@codemirror/view 0.19.3 (2021-08-25)
Bug fixes
Fix a view corruption that could happen in situations involving overlapping mark decorations.
```

**Comment by Nexucis** [comment]
yes of course we should do it. But right now, I would prefer to wait a bit.
We migrated the code to prometheus directly, and we are working on making this repo a mirror. I hope we will be able to release a new version soon.

There are other changes that required to be released too and there are not in this repository. So to avoid a desync between this repo and prometheus, I would prefer to wait the automatic synchronization that is coming.

Code is there: https://github.com/prometheus/prometheus/tree/main/web/ui/module/codemirror-promql

**Comment by Nexucis** [comment]
@dsmith3197 I started to upgrade codemirror to the last version, looks like the behavior of lezer changed a bit resulting of some tests that failed. Hope it won't take too much time to upgrade it ...
