### ISSUE TITLE
Offline mode parser error false positives 

### ISSUE THREAD

**Issue by slrtbtfs** [prometheus-community/codemirror-promql#2]
There are some queries that are valid PromQL but will trigger parser errors in this Software. Examples:

* `abs(abs)`
* `sum[5m]`

**Comment by Nexucis** [comment]
Thanks for the highlight :)
Overall I think the offline mode should be deeply review :
* requires e2e test to list all promQL different syntax
* needs to review the parsing to be more accurate. But that's not really simple.

**Comment by slrtbtfs** [comment]
It might be possible to extract the test cases from [this file](https://github.com/prometheus/prometheus/blob/master/promql/parser/parse_test.go) using some advanced `grep` magic.

**Comment by Nexucis** [comment]
at some point, should be fixed through the roadmap #5

**Comment by Nexucis** [comment]
it has been fixed with the PR #35
