### ISSUE TITLE
Text can become hidden behind tooltip

### ISSUE THREAD

**Issue by MacroPower** [prometheus-community/codemirror-promql#44]
The current positions of the diagnostic tooltips seem to be set relative to `start`.

I've noticed that as a result of this, when I have some issue spanning multiple lines, e.g.:
![image](https://user-images.githubusercontent.com/5648814/93522642-cabdb280-f8ff-11ea-99ba-b26ca7acd6f9.png)

The resulting tooltip makes it very difficult to edit the PromQL, as it completely covers part of the query and makes it impossible to click on the areas it covers. (Screenshot is after hovering over "...")
![image](https://user-images.githubusercontent.com/5648814/93522724-e923ae00-f8ff-11ea-9131-20c9391b6b50.png)

Example GIF from PromLens:
![output](https://user-images.githubusercontent.com/5648814/93528970-2d677c00-f909-11ea-8d7e-67bbfeb1823d.gif)

I think ideally this tooltip should either move with the cursor, or be set relative to `end` rather than start. On first glance, I'm not sure if there's any way to do this easily without making changes to codemirror.next, however.

**Comment by dvkndn** [comment]
This is indeed CodeMirror's tooltip. To be specific, `codemirror-promql`'s lint uses `codemirror`'s lint, which uses `codemirror`'s tooltip with the following options:

https://github.com/codemirror/codemirror.next/blob/7aeef2544f9533b646183fe97394de1ead90434f/lint/src/lint.ts#L143-L152

> I think ideally this tooltip should either move with the cursor, or be set relative to end rather than start.

I think an easier approach is to set https://codemirror.net/6/docs/ref/#tooltip.Tooltip.above to `true`. This, however, still require CodeMirror's Lint module to allow us to set that option to Tooltip.

I think we should create an issue in CodeMirror asking for their opinion

**Comment by dvkndn** [comment]
Fixed in upstream https://github.com/codemirror/codemirror.next/commit/d502554db22d48f9d6a4f1e03e3e8629dcc1b589 !
