### ISSUE TITLE
Problems with LSP mode

### ISSUE THREAD

**Issue by dvkndn** [prometheus-community/codemirror-promql#48]
Following #46 , I created this issue to list the problems currently in the LSP mode (at least compare with the Prometheus mode).

Good: Prometheus
![Screenshot from 2020-09-20 03-57-25](https://user-images.githubusercontent.com/5953369/93689123-c1963680-faf5-11ea-9f69-859dba9b6d97.png)

Current bugs in LSP mode:
![Screenshot from 2020-09-20 03-57-44](https://user-images.githubusercontent.com/5953369/93689122-c0650980-faf5-11ea-960d-37ab10c83283.png)
1. [x] Matched text is not highlight
2. [x] Function's score is lower than metrics (actually I think the problem here is fuzzy score is not used?)
3. [ ] No snippet

**Comment by Nexucis** [comment]
> Function's score is lower than metrics (actually I think the problem here is fuzzy score is not used?

It's on promql-langserver side. So filtering and scoring are not coming from cmn since it's on the server side to provide these features. @slrtbtfs can talk a bit more about it I believe :)

**Comment by Nexucis** [comment]
In the PR https://github.com/prometheus-community/codemirror-promql/pull/8 that implements the autocompletion using LSP, there is a bunch of suggestions to improve it. Snippet was mentionned at this time.

There is certainly some code to do here, but also on promql-langserver side.

Hope it helps to clarify a bit the history of this mode / the situation

**Comment by slrtbtfs** [comment]
The sorting order in the LSP mode is provided by the language server, in a way that functions appear first.

Maybe the code in this repo reverses that order, this would explain why the function appears last.

**Comment by dvkndn** [comment]
Doesn't seem like this library uses the score returned by the language server: https://github.com/prometheus-community/codemirror-promql/blob/9e43058bd1341e8b52b0d8dcf1698a59e693b891/src/lang-promql/complete/lsp.ts#L74

**Comment by Nexucis** [comment]
moving to cmn v12 should have fixed the first 2 points

**Comment by dvkndn** [comment]
Yes I confirm the first 2 are fixed :D

**Comment by Nexucis** [comment]
on this particular point, snippet should be implemented on server side. Nothing to do here ;).

**Comment by dvkndn** [comment]
I think we can close this issue then :+1:
