### ISSUE TITLE
Explicitly put nexucis's fork into dependency list

### ISSUE THREAD

**Issue by dvkndn** [prometheus-community/codemirror-promql#49]
I know I can install it myself but I think it's good to put into the dependency anyway since we directly use it

![Screenshot from 2020-09-20 21-49-54](https://user-images.githubusercontent.com/5953369/93714244-94946300-fb8b-11ea-9a41-6ebfe088f169.png)

**Comment by Nexucis** [comment]
Mmm not really. It has been done on purpose. It's the same for the cmn dependency by the way.

Like that you are controlling which version you are going to use. And it helps to avoid to have different version of the same dependency.

And anyway we should go back to the vanilla autocomplete module. So it won't change.

**Comment by dvkndn** [comment]
I'm closing this issue  @Nexucis :+1:
