### ISSUE TITLE
Limit amount of cached autocomplete data

### ISSUE THREAD

**Issue by juliusv** [prometheus-community/codemirror-promql#71]
Currently the Prometheus client never forgets any cached autocomplete data. The amount of series data that can be cached is potentially huge, so keeping all of it forever is basically like a memory leak and can make the browser slow when using the same PromLens tab for a while. It would be good to find a way to expire old items, like an LRU cache method or something like that.

**Comment by Nexucis** [comment]
I guess for this kind of thing, it will be interesting to separate the cache to the `PrometheusClient` like you were suggesting sometimes ago.
