### ISSUE TITLE
how can I config gutter?

### ISSUE THREAD

**Issue by zhoustudent** [prometheus-community/codemirror-promql#96]
[codemirror gutter doc](https://codemirror.net/6/docs/ref/#gutter)
how can I use it in your npm package?
thanks

**Comment by Nexucis** [comment]
Hi,

To strictly answer the question, that's not possible.

But I think that's not exactly what you would like. This package is providing a support of the promQL language as a codemirror extension exactly like the package `gutter` you are talking about.

As everything is an extension in Codemirror 6, you simply have to inject the gutter extension in the configuration of Codemirror itself along with the promQL extension.

[here](https://github.com/prometheus-community/codemirror-promql/blob/master/src/app/app.ts#L49) you have a simple example of how to setup Codemirror 6, injecting the PromQL extension. 
Note that in the example, I don't use directly the gutter package but it is emborded through the [basic-setup](https://github.com/codemirror/basic-setup/blob/main/src/basic-setup.ts#L52) extension

Does it answer the question ?

**Comment by Nexucis** [comment]
I'm closing the issue since I think I have answered  the question. Feel free to reopen it if you are disagree.
